[[constraint]]
    name = "github.com/ic2hrmk/minish"
    version = "=0.2.0"

[[constraint]]
    name = "github.com/tucnak/telebot"
    version = "ver2.0"

[[constraint]]
    name = "github.com/go-ozzo/ozzo-validation"
    version = "=3.5.0"

[prune]
  go-tests = true
  unused-packages = true
